bind = '127.0.0.1:8002'     # bind host:port
workers = 2
timeout = 10
keepalive = 3
# daemon = True
# user = 'amber'
worker_class = 'gevent'     # run in gevent mode
# proc_name = 'gunicorn.proc'
# pidfile = '/home/amber/eForm-Backend/logs/eForm-Resource-0.pid'
# loglevel = 'info'
# accesslog = '/home/amber/eForm-Backend/logs/eForm-Resource-0.log'
# errorlog = '/home/amber/eForm-Backend/logs/eForm-Resource-0.error.log'
